name: Build and deploy Python app to Azure Web App - sump-api

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/main_sump-api.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment and install dependencies
        working-directory: backend
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            backend
            !backend/antenv

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3C7031B922124EC39339E00EE6AAD632 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_67120ECB9A244D2BAA4F73A70DC34814 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_643AE7EB3EA54559BE292C13BB768777 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sump-api'
          slot-name: 'Production'
